pipeline: []
language: pt
policies: []
intents:
- saudacao
- despedida
entities: []
slots: {}
actions: []
forms: {}
e2e_actions: []
responses:
  utter_saudacao:
  - text: Olassssss
  utter_despedida:
  - text: Thauzinho
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
nlu:
- intent: saudacao
  examples: "- hey\n- hello\n- oiis\n- oii\n- olá\n- eai\n"
- intent: despedida
  examples: "- tchau\n- até\n- até mais\n- bye\n"
rules:
- rule: Say goodbye anytime the user says goodbye
  steps:
  - intent: despedida
  - action: utter_despedida
stories:
- story: happy path
  steps:
  - intent: saudacao
  - action: utter_saudacao
  - intent: despedida
  - action: utter_despedida
