pipeline: []
language: pt
policies: []
intents:
- greet
- goodbye
entities: []
slots: {}
actions: []
forms: {}
e2e_actions: []
responses:
  utter_greet:
  - text: Hey! How are you?
  utter_goodbye:
  - text: Bye
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
nlu:
- intent: greet
  examples: "- hey\n- hello\n"
- intent: goodbye
  examples: "- bye\n- goodbye\n"
rules:
- rule: Say goodbye anytime the user says goodbye
  steps:
  - intent: goodbye
  - action: utter_goodbye
stories:
- story: happy path
  steps:
  - intent: greet
  - action: utter_greet
  - intent: goodbye
  - action: utter_goodbye
